language: android
sudo: false
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-support
  - extra-android-m2repository
script:
- ant release
deploy:  
  provider: releases
  api_key:
    secure: c5806a7689c9460ce18f90baa6ee0ddc019b89dd
  file: bin/TestLombok.apk
  skip_cleanup: true
  on:
    tags: false